#!/bin/bash
export PATH="$PWD/.buildcache/bin:$PATH"
set -x -e -o pipefail
go generate -run=INSTALL
go generate -skip=INSTALL

shellcheck scripts/*

golangci-lint run

gotestsum -- -race -timeout=60s "$@" ./...
