name: CI/CD

on:
  push:
    branches: master
  pull_request:
    branches: master
  schedule:
    - cron: '0 12 * * 6'

jobs:

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        go:
          - '1.21.0-rc.2' # Also used for goveralls.
          - 'tip'

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        if: matrix.go != 'tip'
        with:
          go-version: ${{ matrix.go }}
          check-latest: true

      - name: Install Go tip
        if: matrix.go == 'tip'
        run: |
          mkdir "$HOME/gotip"
          curl -sL https://storage.googleapis.com/go-build-snap/go/linux-amd64/$(git ls-remote https://github.com/golang/go.git HEAD | awk '{print $1}').tar.gz -o - | tar -C "$HOME/gotip" -xzf -
          echo "GOROOT=$HOME/gotip" >> $GITHUB_ENV
          echo "$HOME/gotip/bin" >> $GITHUB_PATH

      - name: Setup cache for Go tip
        uses: actions/cache@v3
        if: matrix.go == 'tip'
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: v1-go-${{ runner.os }}-tip-${{ hashFiles('go.sum') }}
          restore-keys: |
            v1-go-${{ runner.os }}-tip-

      - run: go version

      - name: Setup cache for tools
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/golangci-lint
            .buildcache
          key: v1-tools-${{ runner.os }}-${{ matrix.go }}-${{ hashFiles('tools.go') }}
          restore-keys: |
            v1-tools-${{ runner.os }}-${{ matrix.go }}-

      - run: go generate
#     - run: .buildcache/bin/golangci-lint run
      - run: go test -race ./...

      - name: Report code coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
        if: env.COVERALLS_TOKEN && matrix.go == '1.21.0-rc.2'
        run: .buildcache/bin/goveralls -service=GitHub
